const GET_DATA = "GET_DATA";
const SET_DATA = "SET_DATA";

const GET_COLLAPSE = "GET_COLLAPSE"
const SET_COLLAPSE = "SET_COLLAPSE"

const GET_BREADLIST = "GET_BREADLIST"
const SET_BREADLIST = "SET_BREADLIST"


export { GET_DATA, SET_DATA, GET_COLLAPSE, SET_COLLAPSE, GET_BREADLIST, SET_BREADLIST }